---
  - name: Download Openoffice
    get_url: url=https://archive.apache.org/dist/openoffice/4.0.0/binaries/en-US/Apache_OpenOffice_4.0.0_Linux_x86-64_install-deb_en-US.tar.gz dest=~/OpenOffice.tar.gz
    register: get_url_result
  
  - name: Install Openoffice Install script
    copy: src=office_install.sh dest=/tmp/office_install.sh mode=0755
    when: get_url_result.changed

  - name: Run Openoffice Install script
    command: /tmp/office_install.sh
    when: get_url_result.changed

  - name: Download Openoffice SDK
    get_url: url=https://archive.apache.org/dist/openoffice/4.0.0/binaries/SDK/Apache_OpenOffice-SDK_4.0.0_Linux_x86-64_install-deb_en-US.tar.gz dest=~/OpenOffice-SDK.tar.gz
    register: get_url_result
  
  - name: Install Openoffice SDK Install script
    copy: src=office_sdk_install.sh dest=/tmp/office_sdk_install.sh mode=0755
    when: get_url_result.changed

  - name: Run Openoffice SDK Install script
    command: /tmp/office_sdk_install.sh
    when: get_url_result.changed

  - name: Create symlink to soffice
    file: src=/opt/openoffice4/program/soffice dest=/usr/bin/soffice state=link

